### ISSUE TITLE
Test Suite Division by 0 with uncertainty

### ISSUE THREAD

**Issue by zacharyjhumphrey** [JALusk/SuperBoL#12]
In one of the test cases, a division by zero occurs because the uncertainty of the flux is set to 0 on two fluxes in this [test case](https://github.com/JALusk/SuperBoL/blob/474f4957c5abc29863cd776be5264e8a86a8a8ba/tests/unit/test_lqbol.py#L37) 
As a result, when the code tries to [get the weights](https://github.com/JALusk/SuperBoL/blob/474f4957c5abc29863cd776be5264e8a86a8a8ba/superbol/sed.py#L62) a division by zero occurs. 

Some sort of test case needs to be created to prevent this from happening again, but I'm not familiar enough with the physics to create a solution on my own.

**Comment by JALusk** [comment]
Test case created to catch the ZeroDivisionError, and the code has been modified to separate the SED creation from the quasi-bolometric luminosity calculation
